### PR TITLE
create Category

### PR DESCRIPTION
**Pull request by GoppysoulFrisk**
I've done everything related to the Category: services, DTO, RestController, Entity

### CODE REVIEW

**Comment by taniakysla** [comment]
Review report:
1. Include task number and short title to fork name
2. Include task number and full title (as in task) to commit, exp. [#9] - User registration API
3. Add null check where use streams
4. Entity:
    - category name should not be unique 
    - id, parentId is long
 5. Repository: -
 6. CategoryService:
    - remove unneeded implementations
 7. Controller: -
 8. DTO
   - id, parentId is long
 9.
   - id should not be mapped in dto to entity method if category is creating, can force set id as null in controller before mapping

**Review by GoppysoulFrisk — COMMENTED** [review]
#8 - Category Entities and API

**Comment by taniakysla** [comment]
Review report:
1. Include task number and full title (as in task) to commit, ex. [#9] - User registration API don't forget brackets []
2. Add null check where use streams** pls also check method categoryRepository.findRootCategories(); can it be null if no data in database?
3. Entity:
- category name should not be unique
4. Repository: since category name is not unique method findCategoryByName make no sense and can be removed (we do not use it anyway elsewhere) 
5. CategoryService:
- hibernate returns child categories,  so extract just root categories should be enough. Did you check this with deeper tree? however we can keep recursive method as good sample for job interview, up to you
6. add logging messages `public static final Logger LOG = LoggerFactory.getLogger(Example.class)`

**Review by taniakysla — APPROVED** [review]
well done!

**Pull request merged**
